name: flutter_circle_color_picker
description: A circle color picker for flutter.
version: 0.0.1
author: Takeshi Tsukamoto <itometeam@gmail.com>
homepage: https://github.com/itome/flutter_circle_color_picker

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
